### ISSUE TITLE
JAVA DXA1.4 Error Universe must not be null or empty

### ISSUE THREAD

**Issue by vivekdhiman** [sdl/dxa-modules#22]
While connecting the smart target in tridion, I am getting the below error. Can someone tell me the debugging tips for the same issue.
`java.lang.IllegalArgumentException: Universe must not be null or empty
    at com.tridion.smarttarget.entitymodel.query.Query.<init>(Query.java:263) ~[smarttarget_entitymodel-8.1.1.jar:8.1.1]
    at com.tridion.smarttarget.query.builder.QueryBuilder.<init>(QueryBuilder.java:128) ~[smarttarget_core-8.1.1.jar:8.1.1]
    at com.tridion.smarttarget.query.builder.QueryBuilder.<init>(QueryBuilder.java:112) ~[smarttarget_core-8.1.1.jar:8.1.1]
    at com.sdl.dxa.modules.smarttarget.mapping.SmartTargetPageBuilder.executeSmartTargetQuery(SmartTargetPageBuilder.java:166) ~[dxa-module-smarttarget-web8-1.4.1.jar:1.4.1]
    at com.sdl.dxa.modules.smarttarget.mapping.SmartTargetPageBuilder.processQueryAndPromotions(SmartTargetPageBuilder.java:135) ~[dxa-module-smarttarget-web8-1.4.1.jar:1.4.1]
    at com.sdl.dxa.modules.smarttarget.mapping.AbstractSmartTargetPageBuilder.createPage(AbstractSmartTargetPageBuilder.java:161) ~[dxa-module-smarttarget-abstract-1.4.1.jar:1.4.1]
    at com.sdl.webapp.tridion.mapping.ModelBuilderPipeline.createPageModel(ModelBuilderPipeline.java:72) ~[dxa-tridion-provider-1.4.1.jar:1.0-SNAPSHOT]
    at com.sdl.webapp.tridion.mapping.AbstractDefaultProvider$1.tryFindPage(AbstractDefaultProvider.java:287) ~[dxa-tridion-provider-1.4.1.jar:1.0-SNAPSHOT]
    at com.sdl.webapp.tridion.mapping.AbstractDefaultProvider$1.tryFindPage(AbstractDefaultProvider.java:267) ~[dxa-tridion-provider-1.4.1.jar:1.0-SNAPSHOT]
    at com.sdl.webapp.tridion.mapping.AbstractDefaultProvider.findPage(AbstractDefaultProvider.java:102) ~[dxa-tridion-provider-1.4.1.jar:1.0-SNAPSHOT]
    at com.sdl.webapp.tridion.mapping.AbstractDefaultProvider.getPageModel(AbstractDefaultProvider.java:267) ~[dxa-tridion-provider-1.4.1.jar:1.0-SNAPSHOT]
    at com.sdl.webapp.common.controller.PageController.getPageModel(PageController.java:321) ~[dxa-common-api-1.4.1.jar:1.4.1]
    at com.sdl.webapp.common.controller.PageController.handleGetPage(PageController.java:129) ~[dxa-common-api-1.4.1.jar:1.4.1]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_121]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_121]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_121]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_121]
`
Even when I rename the smarttarget_conf, same error coming. So i think might be connection is not loading this file

**Comment by rpannekoek** [comment]
Please only report known issues here; questions should go on Tridion Stack Exchange.
