### ISSUE TITLE
Sdl.Web.Common.DxaException: No View Model registered for View Ish:Page:GeneralPage - Error

### ISSUE THREAD

**Issue by avmgan** [sdl/dxa-modules#34]
Hi,

I was trying to prepare the OOTB DXA 2.2 (with latest HF) + DD Module 2.2, It was not working and getting this below error message.

just to add my findings I too validate with DXA .NET 2.1 + DD Module - it's working fine.

Steps to reproduce:
I did download the sources and modules from github here as of 22nd Apr 2020.

https://github.com/sdl/dxa-web-application-dotnet/tree/release/2.2
https://github.com/sdl/dxa-modules/tree/release/2.2
https://github.com/sdl/dxa-modules/releases/download/DXA_2.2.2_Hotfix/SDL.DXA.DynamicDocumentation.Module.2.2.2.zip

Sdl.Web.Common.DxaException: No View Model registered for View 'Ish:Page:GeneralPage'. Check that you have registered this View in the 'Ish' area registration.
   at Sdl.Web.Common.Models.ModelTypeRegistry.GetViewModelType(MvcData viewData) in C:\Workspace\SDL-Tridion-Docs\DDWebapp\dxa-web-application-dotnet-release-2.2\Sdl.Web.Common\Models\ModelTypeRegistry.cs:line 115
   at Sdl.Web.Tridion.Mapping.DefaultModelBuilder.BuildPageModel(PageModel& pageModel, PageModelData pageModelData, Boolean includePageRegions, Localization localization) in C:\Workspace\SDL-Tridion-Docs\DDWebapp\dxa-web-application-dotnet-release-2.2\Sdl.Web.Tridion\Mapping\DefaultModelBuilder.cs:line 75
   at Sdl.Web.Tridion.Mapping.ModelBuilderPipeline.CreatePageModel(PageModelData pageModelData, Boolean includePageRegions, Localization localization) in C:\Workspace\SDL-Tridion-Docs\DDWebapp\dxa-web-application-dotnet-release-2.2\Sdl.Web.Tridion\Mapping\ModelBuilderPipeline.cs:line 132
   at Sdl.Web.Tridion.Mapping.DefaultContentProvider.LoadPageModel(Int32 pageId, Boolean addIncludes, Localization localization) in C:\Workspace\SDL-Tridion-Docs\DDWebapp\dxa-web-application-dotnet-release-2.2\Sdl.Web.Tridion\Providers\DefaultContentProvider.cs:line 362
   at Sdl.Web.Tridion.Mapping.DefaultContentProvider.<>c__DisplayClass2_1.<GetPageModel>b__0() in C:\Workspace\SDL-Tridion-Docs\DDWebapp\dxa-web-application-dotnet-release-2.2\Sdl.Web.Tridion\Providers\DefaultContentProvider.cs:line 104
   at Sdl.Web.Tridion.Caching.CacheProvider.CreateCacheValue[T](UInt32 hash, String key, String region, Func`1 addFunction, IEnumerable`1 dependencies) in C:\Workspace\SDL-Tridion-Docs\DDWebapp\dxa-web-application-dotnet-release-2.2\Sdl.Web.Tridion\Providers\Caching\CacheProvider.cs:line 133
   at Sdl.Web.Tridion.Caching.CacheProvider.GetOrAdd[T](String key, String region, Func`1 addFunction, IEnumerable`1 dependencies) in C:\Workspace\SDL-Tridion-Docs\DDWebapp\dxa-web-application-dotnet-release-2.2\Sdl.Web.Tridion\Providers\Caching\CacheProvider.cs:line 86
   at Sdl.Web.Tridion.Caching.DefaultCacheProvider.GetOrAdd[T](String key, String region, Func`1 addFunction, IEnumerable`1 dependencies) in C:\Workspace\SDL-Tridion-Docs\DDWebapp\dxa-web-application-dotnet-release-2.2\Sdl.Web.Tridion\Providers\Caching\DefaultCacheProvider.cs:line 63
   at Sdl.Web.Tridion.Mapping.DefaultContentProvider.GetPageModel(Int32 pageId, Localization localization, Boolean addIncludes) in C:\Workspace\SDL-Tridion-Docs\DDWebapp\dxa-web-application-dotnet-release-2.2\Sdl.Web.Tridion\Providers\DefaultContentProvider.cs:line 99
   at Sdl.Web.Modules.DynamicDocumentation.Controllers.ApiController.Page(Int32 publicationId, Int32 pageId) in C:\Workspace\SDL-Tridion-Docs\DDWebapp\dxa-web-application-dotnet-release-2.2\DynamicDocumentation\Controllers\ApiController.cs:line 72
Sdl.Web.Common.DxaException: No View Model registered for View 'Ish:Page:GeneralPage'. Check that you have registered this View in the 'Ish' area registration.
   at Sdl.Web.Common.Models.ModelTypeRegistry.GetViewModelType(MvcData viewData) in C:\Workspace\SDL-Tridion-Docs\DDWebapp\dxa-web-application-dotnet-release-2.2\Sdl.Web.Common\Models\ModelTypeRegistry.cs:line 115
   at Sdl.Web.Tridion.Mapping.DefaultModelBuilder.BuildPageModel(PageModel& pageModel, PageModelData pageModelData, Boolean includePageRegions, Localization localization) in C:\Workspace\SDL-Tridion-Docs\DDWebapp\dxa-web-application-dotnet-release-2.2\Sdl.Web.Tridion\Mapping\DefaultModelBuilder.cs:line 75
   at Sdl.Web.Tridion.Mapping.ModelBuilderPipeline.CreatePageModel(PageModelData pageModelData, Boolean includePageRegions, Localization localization) in C:\Workspace\SDL-Tridion-Docs\DDWebapp\dxa-web-application-dotnet-release-2.2\Sdl.Web.Tridion\Mapping\ModelBuilderPipeline.cs:line 132
   at Sdl.Web.Tridion.Mapping.DefaultContentProvider.LoadPageModel(Int32 pageId, Boolean addIncludes, Localization localization) in C:\Workspace\SDL-Tridion-Docs\DDWebapp\dxa-web-application-dotnet-release-2.2\Sdl.Web.Tridion\Providers\DefaultContentProvider.cs:line 362
   at Sdl.Web.Tridion.Mapping.DefaultContentProvider.<>c__DisplayClass2_1.<GetPageModel>b__0() in C:\Workspace\SDL-Tridion-Docs\DDWebapp\dxa-web-application-dotnet-release-2.2\Sdl.Web.Tridion\Providers\DefaultContentProvider.cs:line 104
   at Sdl.Web.Tridion.Caching.CacheProvider.CreateCacheValue[T](UInt32 hash, String key, String region, Func`1 addFunction, IEnumerable`1 dependencies) in C:\Workspace\SDL-Tridion-Docs\DDWebapp\dxa-web-application-dotnet-release-2.2\Sdl.Web.Tridion\Providers\Caching\CacheProvider.cs:line 133
   at Sdl.Web.Tridion.Caching.CacheProvider.GetOrAdd[T](String key, String region, Func`1 addFunction, IEnumerable`1 dependencies) in C:\Workspace\SDL-Tridion-Docs\DDWebapp\dxa-web-application-dotnet-release-2.2\Sdl.Web.Tridion\Providers\Caching\CacheProvider.cs:line 86
   at Sdl.Web.Tridion.Caching.DefaultCacheProvider.GetOrAdd[T](String key, String region, Func`1 addFunction, IEnumerable`1 dependencies) in C:\Workspace\SDL-Tridion-Docs\DDWebapp\dxa-web-application-dotnet-release-2.2\Sdl.Web.Tridion\Providers\Caching\DefaultCacheProvider.cs:line 63
   at Sdl.Web.Tridion.Mapping.DefaultContentProvider.GetPageModel(Int32 pageId, Localization localization, Boolean addIncludes) in C:\Workspace\SDL-Tridion-Docs\DDWebapp\dxa-web-application-dotnet-release-2.2\Sdl.Web.Tridion\Providers\DefaultContentProvider.cs:line 99
   at Sdl.Web.Modules.DynamicDocumentation.Controllers.ApiController.Page(Int32 publicationId, Int32 pageId) in C:\Workspace\SDL-Tridion-Docs\DDWebapp\dxa-web-application-dotnet-release-2.2\DynamicDocumentation\Controllers\ApiController.cs:line 72

**Comment by avmgan** [comment]
It was my fualt. I did place it in the last.

Domentation is indeed.

In the modelBuilderPipeline section, add the Dynamic Documentation model builder to the pipeline, placing it first in the list and before the Default model builder, as the following example illustrates:

<modelBuilderPipeline>
   <add type="Sdl.Web.Modules.DynamicDocumentation.Mapping.ModelBuilder, Sdl.Web.Modules.DynamicDocumentation" />
   <add type="Sdl.Web.Tridion.Mapping.DefaultModelBuilder, Sdl.Web.Tridion" />
   ...
   ...
 </modelBuilderPipeline>

**Comment by avmgan** [comment]
It was my fualt. I did place it in the last.

Domentation is indeed.

In the modelBuilderPipeline section, add the Dynamic Documentation model builder to the pipeline, placing it first in the list and before the Default model builder, as the following example illustrates:

<modelBuilderPipeline>
   <add type="Sdl.Web.Modules.DynamicDocumentation.Mapping.ModelBuilder, Sdl.Web.Modules.DynamicDocumentation" />
   <add type="Sdl.Web.Tridion.Mapping.DefaultModelBuilder, Sdl.Web.Tridion" />
   ...
   ...
 </modelBuilderPipeline>
